Cross mio updates to vocab.csv
WHOIGit/ooicgsn-asset-management pull request #1194
Opened 2023-06-27 17:30 UTC by rtravis-whoi

Updated vocab.csv as part of METBK sensor project - added sensors to SMs and a few other minor updates as noted in vocab_METBK_additions_2023-06-27_FINAL.xlsx (attached).  Also refer to the added highlighted columns in attached spreadsheet to verify metbk module heights.

[METBK_Module_Heights_RGT_2023-06-27.xlsx](https://github.com/WHOIGit/ooicgsn-asset-management/files/11885555/METBK_Module_Heights_RGT_2023-06-27.xlsx)

2023-06-27 20:25 UTC, rtravis-whoi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Look into ingesting METBK-CT recovered instrument data (Redmine #14304, #15493) [DT-180]](https://trello.com/c/sSSfBQmE/180-look-into-ingesting-metbk-ct-recovered-instrument-data-redmine-14304-15493-dt-180)

2023-06-28 14:18 UTC, snwhite requested changes
Cut and Paster error for Pioneer Inshore and Offshore need to be corrected.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +CP01CNSM-SBD11-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +CP01CNSM-SBD12-08-FDCHPA000,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Direct Covariance Flux,WHOI,DCFS,-5,-5
Looks good.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +CP03ISSM-SBD11-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Should say "Inshore" not "Central"

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +CP04OSSM-SBD11-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Should say "Offshore" not "Central"

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +GA01SUMO-SBD11-06-METBKA001,Global Argentine Basin,Apex Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Sea-Bird Electronics,ASIMET-SBE37SM,1,1
Looks good.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +GI01SUMO-SBD11-06-METBKA007,Global Irminger Sea,Apex Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-6,-6
Looks good.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +GI01SUMO-SBD12-08-FDCHPA000,Global Irminger Sea,Apex Surface Mooring,Surface Buoy,Direct Covariance Flux,WHOI,DCFS,-6,-6
Looks good.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +GS01SUMO-SBD11-06-METBKA007,Global Southern Ocean,Apex Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-6,-6
Looks good.

2023-06-28 14:18 UTC, snwhite commented on vocab/vocab.csv
> +GS01SUMO-SBD12-08-FDCHPA000,Global Southern Ocean,Apex Surface Mooring,Surface Buoy,Direct Covariance Flux,WHOI,DCFS,-6,-6
Looks good.

2023-06-28 14:31 UTC, rtravis-whoi commented on vocab/vocab.csv
> +CP04OSSM-SBD11-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
correction made

2023-06-28 14:32 UTC, rtravis-whoi commented on vocab/vocab.csv
> +CP03ISSM-SBD11-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
correction made

2023-06-28 14:38 UTC, snwhite approved these changes

2023-06-28 14:38 UTC, snwhite commented on vocab/vocab.csv
> +CP03ISSM-SBD11-06-METBKA007,Coastal Pioneer,Inshore Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good.

2023-06-28 14:38 UTC, snwhite commented on vocab/vocab.csv
> +CP04OSSM-SBD11-06-METBKA007,Coastal Pioneer,Offshore Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good.

2023-06-28 19:00 UTC, cdobs approved these changes

2023-06-28 19:00 UTC, cdobs commented on vocab/vocab.csv
> +CP01CNSM-SBD11-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good

2023-06-28 19:00 UTC, cdobs commented on vocab/vocab.csv
> +CP01CNSM-SBD12-06-METBKA007,Coastal Pioneer,Central Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good

2023-06-28 19:00 UTC, cdobs commented on vocab/vocab.csv
> +CP03ISSM-SBD11-06-METBKA007,Coastal Pioneer,Inshore Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good

2023-06-28 19:00 UTC, cdobs commented on vocab/vocab.csv
> +CP04OSSM-SBD11-06-METBKA007,Coastal Pioneer,Offshore Surface Mooring,Surface Buoy,Bulk Meteorology Instrument Package,Star Engineering,ASIMET-SWND,-5,-5
Looks good

2023-06-28 19:27 UTC, merged