new cal csvs
WHOIGit/ooicgsn-asset-management pull request #1340
Opened 2024-01-12 15:53 UTC by rtravis-whoi

2024-01-12 15:57 UTC, rtravis-whoi commented
![](https://github.trello.services/images/mini-trello-icon.png) [PY VI Instrument Cal CSVs [DT-219]](https://trello.com/c/CkLoKMMl/219-py-vi-instrument-cal-csvs-dt-219)

2024-01-25 16:04 UTC, cdobs requested changes
Just one small change requested: update source file name in CGINS-CTDBPD-50110__20231107.csv

2024-01-25 16:04 UTC, cdobs commented on calibration/OPTAAD/CGINS-OPTAAD-00207__20231218__CC_taarray.ext
> +-0.000333,-0.000329,-0.000453,-0.000520,-0.000796,-0.001095,-0.000666,-0.000028,0.000052,-0.000151,-0.000067,-0.000376,-0.000658,-0.000814,-0.000053,-0.000389,-0.000560,-0.000553,-0.000222,-0.000469,
spot checked - looks good

2024-01-25 17:44 UTC, cdobs approved these changes

2024-01-25 17:44 UTC, cdobs commented on calibration/CTDBPD/CGINS-CTDBPD-50110__20231107.csv
> +16-50110,CC_ptempa2,9.283013e-001,
updated source file looks good!

2024-01-25 17:44 UTC, cdobs commented on calibration/DOSTAD/CGINS-DOSTAD-00428__20231129.csv
> +428,CC_csv,"[2.46260E-03, 1.04744E-04, 2.04518E-06, 1.66805E+02, -2.19485E-01, -4.05650E+01, 3.37945E+00]",
updated format looks good!

2024-01-26 22:04 UTC, cooleyky commented on calibration/OPTAAD/CGINS-OPTAAD-00207__20231218__CC_taarray.ext
> +-0.000333,-0.000329,-0.000453,-0.000520,-0.000796,-0.001095,-0.000666,-0.000028,0.000052,-0.000151,-0.000067,-0.000376,-0.000658,-0.000814,-0.000053,-0.000389,-0.000560,-0.000553,-0.000222,-0.000469,
spot checked, looks good

2024-01-26 22:08 UTC, cooleyky commented on calibration/OPTAAD/CGINS-OPTAAD-00207__20231218__CC_tcarray.ext
> +0.008608,0.011053,0.014258,0.013475,0.013021,0.012689,0.010997,0.010267,0.009886,0.009345,0.008723,0.008077,0.007507,0.007101,0.006643,0.006313,0.005463,0.005085,0.004403,0.004027,0.003237,0.002550,0
spot checked, looks good

2024-01-29 20:21 UTC, merged