New CTDMO cal csvs
WHOIGit/ooicgsn-asset-management pull request #1394
Opened 2024-02-02 21:42 UTC by rtravis-whoi

2024-02-07 17:07 UTC, rtravis-whoi commented
![](https://github.trello.services/images/mini-trello-icon.png) [PY VI Instrument Cal CSVs [DT-219]](https://trello.com/c/CkLoKMMl/219-py-vi-instrument-cal-csvs-dt-219)

2024-02-13 20:53 UTC, cooleyky reviewed
Posting my comments for a review in progress in case someone else can finish this review before I can. I reviewed the first 17 CTDMOGs through 11610

2024-02-13 22:09 UTC, nichole-arm reviewed
Finished first 26/38 file reviews. last one completed was CGINS-CTDMO-11681.

2024-02-13 22:09 UTC, nichole-arm commented on calibration/CTDMOH/CGINS-CTDMOH-11681__20240119.csv
looks good

2024-02-16 19:45 UTC, cdobs requested changes
One small change needed on CGINS-CTDMOS-12304__20231103.csv

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOG/CGINS-CTDMOG-11647__20240123.csv
> +37-11647,CC_p_range,1450,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOH/CGINS-CTDMOH-10228__20240121.csv
> +37-10228,CC_p_range,5076,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOH/CGINS-CTDMOH-11601__20240119.csv
> +37-11601,CC_p_range,5076,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOH/CGINS-CTDMOH-11602__20240121.csv
> +37-11602,CC_p_range,5076,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOH/CGINS-CTDMOH-11681__20240119.csv
> +37-11681,CC_p_range,5076,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOH/CGINS-CTDMOH-11682__20240120.csv
> +37-11682,CC_p_range,5076,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOH/CGINS-CTDMOH-11683__20240123.csv
> +37-11683,CC_p_range,5076,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-11641__20231103.csv
> +37-11641,CC_wbotc,-3.428080e-008,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-11648__20231103.csv
> +37-11648,CC_wbotc,7.421541e-007,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-12304__20231103.csv
> +37-12304,CC_wbotc,1.395213e-007,
Row 24 needs a comma at the end, otherwise looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-12331__20231109.csv
> +37-12331,CC_wbotc,4.864379e-007,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-12337__20231109.csv
> +37-12337,CC_wbotc,3.482517e-008,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-12402__20231103.csv
> +37-12402,CC_wbotc,6.757779e-007,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-13559__20231103.csv
> +37-13559,CC_wbotc,-5.808349e-007,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-13558__20231108.csv
> +37-13558,CC_wbotc,2.163058e-007,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-13378__20231103.csv
> +37-13378,CC_wbotc,1.543480e-007,
looks good

2024-02-16 19:45 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-12585__20231109.csv
> +37-12585,CC_wbotc,3.899884e-007,
looks good

2024-02-16 19:53 UTC, cdobs approved these changes

2024-02-16 19:53 UTC, cdobs commented on calibration/CTDMOS/CGINS-CTDMOS-12304__20231103.csv
> +37-12304,CC_wbotc,1.395213e-007,
looks good!

2024-02-21 15:55 UTC, reedan88 approved these changes
Picked up where Nikki left off. Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOH/CGINS-CTDMOH-11682__20240120.csv
> +37-11682,CC_p_range,5076,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOH/CGINS-CTDMOH-11683__20240123.csv
> +37-11683,CC_p_range,5076,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-11641__20231103.csv
> +37-11641,CC_wbotc,-3.428080e-008,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-11648__20231103.csv
> +37-11648,CC_wbotc,7.421541e-007,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-12304__20231103.csv
> +37-12304,CC_wbotc,1.395213e-007,
Looks good

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-12331__20231109.csv
> +37-12331,CC_wbotc,4.864379e-007,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-12402__20231103.csv
> +37-12402,CC_wbotc,6.757779e-007,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-13558__20231108.csv
> +37-13558,CC_wbotc,2.163058e-007,
Looks good.

2024-02-21 15:55 UTC, reedan88 commented on calibration/CTDMOS/CGINS-CTDMOS-13559__20231103.csv
> +37-13559,CC_wbotc,-5.808349e-007,
Looks good.

2024-02-21 15:58 UTC, merged