Pioneer MAB pre-cruise deploy csvs
WHOIGit/ooicgsn-asset-management pull request #1426
Opened 2024-02-27 14:42 UTC by rtravis-whoi

pre-cruise deploy csvs:
CP10CNSM
CP13EAPM
CP13NOPM

Refer to config sheets in Pioneer 20 Deployment folder in Vault, and attached marine infrastructure and refdes excel file.

2024-02-27 17:27 UTC, rtravis-whoi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pioneer 20 AM Updates](https://trello.com/c/22LKGqi6/232-pioneer-20-am-updates)

2024-02-27 19:34 UTC, reedan88 requested changes
I think the longitude for EAPM is incorrect.

2024-02-27 19:34 UTC, reedan88 commented on deployment/CP10CNSM_Deploy.csv
> +AR82,,,,CP10CNSM-MFD37-07-ZPLSCC000,1,1,2024-02-26T12:00:00,,CGMCP-10CNSM-00001,,CGINS-ZPLSCC-55102,35.95,-75.125,,29,30,,,
Looks good.

2024-02-27 19:34 UTC, reedan88 commented on deployment/CP13NOPM_Deploy.csv
> +AR82,,,,CP13NOPM-WFP01-05-PARADK000,1,1,2024-02-26T12:00:00,,CGMCP-13NOPM-00001,CGVEH-CWFPCP-71401,CGINS-PARADK-20525,36.175,-74.8267,,81,100,,,
Looks good.

2024-02-27 19:48 UTC, reedan88 approved these changes
EAPM longitude fixed. Looks good!

2024-02-27 19:48 UTC, reedan88 commented on deployment/CP13EAPM_Deploy.csv
> +AR82,,,,CP13EAPM-WFP01-05-PARADK000,1,1,2024-02-26T12:00:00,,CGMCP-13EAPM-00001,CGVEH-CWFPCP-99101,CGINS-PARADK-20541,35.95,-74.8457,,81,100,,,
Looks good now!

2024-02-27 22:40 UTC, cdobs approved these changes

2024-02-27 22:40 UTC, cdobs commented on deployment/CP10CNSM_Deploy.csv
> +AR82,,,,CP10CNSM-MFD37-07-ZPLSCC000,1,1,2024-02-26T12:00:00,,CGMCP-10CNSM-00001,,CGINS-ZPLSCC-55102,35.95,-75.125,,29,30,,,
looks good

2024-02-27 22:40 UTC, cdobs commented on deployment/CP12CNSW_Deploy.csv
> +AR82,,,,CP12CNSW-MFI01-02-WAVSSQ010,1,1,2024-03-01T00:00:00,,CGMCP-12CNSW-00001,,CGINS-WAVSSQ-01035,35.9500,-75.125,,30,30,,,
looks good

2024-02-27 22:40 UTC, cdobs commented on deployment/CP12WESW_Deploy.csv
> +AR82,,,,CP12WESW-MFI01-02-WAVSSQ010,1,1,2024-03-01T00:00:00,,,CGMCP-12WESW-00001,CGINS-WAVSSQ-01036,35.9500,-75.3333,,30,30,,,
looks good

2024-02-27 22:40 UTC, cdobs commented on deployment/CP13EAPM_Deploy.csv
> +AR82,,,,CP13EAPM-WFP01-05-PARADK000,1,1,2024-02-26T12:00:00,,CGMCP-13EAPM-00001,CGVEH-CWFPCP-99101,CGINS-PARADK-20541,35.95,-74.8457,,81,100,,,
looks good

2024-02-27 22:40 UTC, cdobs commented on deployment/CP13NOPM_Deploy.csv
> +AR82,,,,CP13NOPM-WFP01-05-PARADK000,1,1,2024-02-26T12:00:00,,CGMCP-13NOPM-00001,CGVEH-CWFPCP-71401,CGINS-PARADK-20525,36.175,-74.8267,,81,100,,,
looks good

2024-02-28 17:51 UTC, reedan88 approved these changes
CP12CNSW and CP12WESW look good.

2024-02-28 17:51 UTC, reedan88 commented on deployment/CP12CNSW_Deploy.csv
> +AR82,,,,CP12CNSW-MFI01-02-WAVSSQ010,1,1,2024-03-01T00:00:00,,CGMCP-12CNSW-00001,,CGINS-WAVSSQ-01035,35.9500,-75.125,,30,30,,,
Looks good.

2024-02-28 17:51 UTC, reedan88 commented on deployment/CP12WESW_Deploy.csv
> +AR82,,,,CP12WESW-MFI01-02-WAVSSQ010,1,1,2024-03-01T00:00:00,,,CGMCP-12WESW-00001,CGINS-WAVSSQ-01036,35.9500,-75.3333,,30,30,,,
Looks good.

2024-02-28 18:19 UTC, merged