Papa 7a glider cals
WHOIGit/ooicgsn-asset-management pull request #459
Opened 2020-10-02 16:08 UTC by cdobs

Papa 7a glider cals

2020-10-02 17:22 UTC, rtravis-whoi requested changes
just need to add -A to source file for NUTNRM-00350 (that was my fault...)

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/CTDGVM/CGINS-CTDGVM-09288__20190329.csv
> +9288,CC_calibration_date,1553817600000,sensor calibration date (milliseconds since 1970-01-01)
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/CTDGVM/CGINS-CTDGVM-00104__20200322.csv
> +104,CC_calibration_date,1584835200000,sensor calibration date (milliseconds since 1970-01-01)
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/DOSTAM/CGINS-DOSTAM-00341__20200305.csv
> +341,CC_calibration_date,1583366400000,sensor calibration date (milliseconds since 1970-01-01)
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/DOSTAM/CGINS-DOSTAM-00537__20200211.csv
> +537,CC_calibration_date,1581379200000,sensor calibration date (milliseconds since 1970-01-01)
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/FLORDM/CGINS-FLORDM-03063__20200429.csv
> +3063,CC_scattering_angle,140.0,
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/FLORTM/CGINS-FLORTM-04039__20190326.csv
> +4039,CC_scattering_angle,124,
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/FLORTO/CGINS-FLORTO-01333__20190327.csv
> +1333,CC_scattering_angle,124,
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/NUTNRM/CGINS-NUTNRM-00661__20200106.csv
> +661,CC_wl,"[188.96, 189.76, 190.56, 191.35, 192.15, 192.95, 193.75, 194.55, 195.35, 196.15, 196.95, 197.76, 198.56, 199.36, 200.16, 200.96, 201.76, 202.56, 203.37, 204.17, 204.97, 205.78, 206.58, 207
looks good

2020-10-02 17:22 UTC, rtravis-whoi commented on calibration/NUTNRM/CGINS-NUTNRM-00350__20200915.csv
> +350,CC_cal_temp,20.00, source_file 3305-00327-00107_SN_350_Pre-Deployment_NUTNR-M.zip > SNA0350E.CAL
source_file should be 3305-00327-00107-A...

2020-10-02 17:36 UTC, rtravis-whoi commented on calibration/NUTNRM/CGINS-NUTNRM-00350__20200915.csv
> +350,CC_wl,"[189.69, 190.47, 191.26, 192.04, 192.83, 193.61, 194.39, 195.18, 195.97, 196.75, 197.54, 198.32, 199.11, 199.9, 200.69, 201.47, 202.26, 203.05, 203.84, 204.63, 205.42, 206.2, 206.99, 207.7
looks good; fixed source_file name.

2020-10-02 17:36 UTC, rtravis-whoi commented on calibration/NUTNRM/CGINS-NUTNRM-00350__20200106.csv
> +350,CC_wl,"[189.69, 190.47, 191.26, 192.04, 192.83, 193.61, 194.39, 195.18, 195.97, 196.75, 197.54, 198.32, 199.11, 199.9, 200.69, 201.47, 202.26, 203.05, 203.84, 204.63, 205.42, 206.2, 206.99, 207.7
looks good

2020-10-02 17:36 UTC, rtravis-whoi approved these changes

2020-10-05 00:06 UTC, snwhite approved these changes
All files look good.

2020-10-05 00:06 UTC, snwhite commented on calibration/NUTNRM/CGINS-NUTNRM-00661__20200106.csv
> +661,CC_wl,"[188.96, 189.76, 190.56, 191.35, 192.15, 192.95, 193.75, 194.55, 195.35, 196.15, 196.95, 197.76, 198.56, 199.36, 200.16, 200.96, 201.76, 202.56, 203.37, 204.17, 204.97, 205.78, 206.58, 207
Looks good.

2020-10-05 00:06 UTC, snwhite commented on calibration/NUTNRM/CGINS-NUTNRM-00350__20200915.csv
> +350,CC_wl,"[189.69, 190.47, 191.26, 192.04, 192.83, 193.61, 194.39, 195.18, 195.97, 196.75, 197.54, 198.32, 199.11, 199.9, 200.69, 201.47, 202.26, 203.05, 203.84, 204.63, 205.42, 206.2, 206.99, 207.7
Looks good.

2020-10-05 00:07 UTC, merged