Cross-mio updates for Pioneer 16
WHOIGit/ooicgsn-asset-management pull request #553
Opened 2021-03-11 22:55 UTC by rtravis-whoi

This PR includes cross-mio updates to the following:
eng_bulk_load-AssetRecord.csv
Addition of UIDs for new platcon on CP03ISSM-13:
CGCON-BCPM01-50015, CGCON-BDCL11-50015, CGCON-BDCL12-50015
Addition of new STC endcap on CP02PMUO-17:
CGCON-BSTC01-00043

sensor_bulk_load-AssetRecord.csv
Addition of new MOPAK on CP02PMUO-17:
CGINS-MOPAK0-70027

CruiseInformation.csv: Addition of Pioneer 16 cruise - AR52

2021-03-11 23:05 UTC, rtravis-whoi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pioneer 16 AM Updates [DT-127]](https://trello.com/c/8zHulE3Q/127-pioneer-16-am-updates-dt-127)

2021-03-12 20:22 UTC, snwhite requested changes
STC full S/N needs to be corrected.

2021-03-12 20:22 UTC, snwhite commented on bulk/eng_bulk_load-AssetRecord.csv
> +CGCON-BSTC01-00043,,Sensor,0,Sensor and Telemetry Platform Controller,Sensor and Telemetry Controller,WHOI,STC,3701-00143-00000-00043,,,,,Woods Hole Oceanographic Institution
The S/N should be 3701-00143-00001-00043  (it's missing the 1 in the third set of numbers).

2021-03-12 20:22 UTC, snwhite commented on bulk/sensor_bulk_load-AssetRecord.csv
> +CGINS-MOPAK0-70027,,Sensor,0,3-Axis Motion Pack: MOPAK,,MicroStrain,3DM-GX3-25,6223-4220-70027,,,,,
In RDB the vendor S/N is listed as 6253-4220.70027.  Should it be a decimal or a dash.  This is a bigger issue we can address later.

2021-03-12 20:22 UTC, snwhite commented on cruise/CruiseInformation.csv
> +AR52,Neil Armstrong,2021-03-29T00:00:00,2021-04-18T23:59:00,Pioneer 16
Looks good.

2021-03-12 20:33 UTC, snwhite approved these changes

2021-03-12 20:33 UTC, snwhite commented on bulk/eng_bulk_load-AssetRecord.csv
> +CGCON-BSTC01-00043,,Sensor,0,Sensor and Telemetry Platform Controller,Sensor and Telemetry Controller,WHOI,STC,3701-00143-00001-00043,,,,,Woods Hole Oceanographic Institution
Correction looks good!

2021-03-12 21:07 UTC, cdobs approved these changes
Everything looks good to me

2021-03-12 21:09 UTC, merged