New Instrument Cal csvs
WHOIGit/ooicgsn-asset-management pull request #694
Opened 2021-08-20 17:34 UTC by rtravis-whoi

PR includes cal csvs for instruments returning from vendor refurb, plus a glider NUTNR post-deploy (Irminger 8).

Additionally there are 2 ADCPAM cal csvs for glider ADCP SNs that had no existing cal csvs (but are in sensor bulk load).  I used the start date of the earliest cruise these were deployed on:
CGINS-ADCPAM-44067 - first deployment on glider 339 on SI20150110
CGINS-ADCPAM-49653 - first deployment on glider 389 on same cruise - SI20150110

2021-08-30 13:48 UTC, IDCalTech commented on calibration/NUTNRB/CGINS-NUTNRB-01091__20210824.csv
> +NTR-1091,CC_upper_wavelength_limit_for_spectra_fit,240,constant
Looks good

2021-08-30 13:48 UTC, IDCalTech commented on calibration/NUTNRB/CGINS-NUTNRB-01094__20210824.csv
> +NTR-1094,CC_upper_wavelength_limit_for_spectra_fit,240,constant
Looks good

2021-08-30 13:48 UTC, IDCalTech commented on calibration/NUTNRM/CGINS-NUTNRM-00661__20210814.csv
> +661,CC_lower_wavelength_limit_for_spectra_fit,217,
Looks good

2021-08-31 22:13 UTC, asmith-whoi requested changes
Change underscore to dash in PHSEN source file name on the original file, and then in the csv. See note below.

2021-08-31 22:13 UTC, asmith-whoi commented on calibration/OPTAAD/CGINS-OPTAAD-00130__20210729.csv
> +ACS-130,CC_tcarray,SheetRef:CC_tcarray,
Good

2021-08-31 22:13 UTC, asmith-whoi commented on calibration/OPTAAD/CGINS-OPTAAD-00130__20210729__CC_taarray.ext
> +0.003078,0.002748,0.002875,0.002971,0.002813,0.002913,0.002751,0.002844,0.002841,0.002714,0.002751,0.002728,0.002665,0.002454,0.00216,0.002026,0.001749,0.001543,0.001297,0.001024,0.000801,0.00072,0.0
Good

2021-08-31 22:13 UTC, asmith-whoi commented on calibration/OPTAAD/CGINS-OPTAAD-00130__20210729__CC_tcarray.ext
> +-0.003639,-0.002027,-0.001124,-0.000947,-0.000877,-0.000796,-0.00071,-0.000721,-0.000523,-0.00037,-0.000212,-0.000133,-0.000181,0.000149,0.000255,0.000152,0.000468,0.000397,0.000419,0.00032,0.000418,
Good

2021-08-31 22:13 UTC, asmith-whoi commented on calibration/OPTAAD/CGINS-OPTAAD-00256__20210811.csv
> +ACS-256,CC_tcarray,SheetRef:CC_tcarray,
Good

2021-08-31 22:13 UTC, asmith-whoi commented on calibration/OPTAAD/CGINS-OPTAAD-00256__20210811__CC_taarray.ext
> +-0.013294,-0.008875,-0.006278,-0.005785,-0.005166,-0.004557,-0.003943,-0.003326,-0.002763,-0.002189,-0.001694,-0.001158,-0.000744,-0.000578,-0.000209,2.3e-05,0.000189,0.000503,0.000635,0.000577,0.000
Good

2021-08-31 22:13 UTC, asmith-whoi commented on calibration/OPTAAD/CGINS-OPTAAD-00256__20210811__CC_tcarray.ext
> +-0.012576,-0.010497,-0.009432,-0.009013,-0.008594,-0.008414,-0.008126,-0.007785,-0.007406,-0.007066,-0.006546,-0.006022,-0.005546,-0.005075,-0.004607,-0.004224,-0.003753,-0.002978,-0.002505,-0.001979
Good

2021-08-31 22:26 UTC, reedan88 approved these changes
Looks good to me.

2021-08-31 22:26 UTC, reedan88 commented on calibration/NUTNRB/CGINS-NUTNRB-01091__20210824.csv
> +NTR-1091,CC_wl,"[187.79, 188.6, 189.41, 190.22, 191.03, 191.84, 192.65, 193.46, 194.27, 195.08, 195.89, 196.71, 197.52, 198.33, 199.14, 199.96, 200.77, 201.58, 202.39, 203.21, 204.02, 204.84, 205.65,
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/NUTNRB/CGINS-NUTNRB-01094__20210824.csv
> +NTR-1094,CC_wl,"[188.81, 189.61, 190.41, 191.21, 192.01, 192.81, 193.61, 194.42, 195.22, 196.02, 196.82, 197.62, 198.42, 199.22, 200.03, 200.83, 201.63, 202.43, 203.23, 204.04, 204.84, 205.64, 206.45
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/NUTNRM/CGINS-NUTNRM-00661__20210814.csv
> +661,CC_wl,"[188.96, 189.76, 190.56, 191.35, 192.15, 192.95, 193.75, 194.55, 195.35, 196.15, 196.95, 197.76, 198.56, 199.36, 200.16, 200.96, 201.76, 202.56, 203.37, 204.17, 204.97, 205.78, 206.58, 207
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/NUTNRM/CGINS-NUTNRM-00760__20210226.csv
> +760,CC_wl,"[189.38, 190.17, 190.96, 191.76, 192.55, 193.35, 194.14, 194.94, 195.73, 196.53, 197.33, 198.12, 198.92, 199.72, 200.51, 201.31, 202.11, 202.91, 203.7, 204.5, 205.3, 206.1, 206.9, 207.7, 2
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00130__20210729.csv
> +ACS-130,CC_tcarray,SheetRef:CC_tcarray,
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00151__20210804.csv
> +ACS-151,CC_tcarray,SheetRef:CC_tcarray,
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00130__20210729__CC_taarray.ext
> +0.003078,0.002748,0.002875,0.002971,0.002813,0.002913,0.002751,0.002844,0.002841,0.002714,0.002751,0.002728,0.002665,0.002454,0.00216,0.002026,0.001749,0.001543,0.001297,0.001024,0.000801,0.00072,0.0
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00130__20210729__CC_tcarray.ext
> +-0.003639,-0.002027,-0.001124,-0.000947,-0.000877,-0.000796,-0.00071,-0.000721,-0.000523,-0.00037,-0.000212,-0.000133,-0.000181,0.000149,0.000255,0.000152,0.000468,0.000397,0.000419,0.00032,0.000418,
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00151__20210804__CC_taarray.ext
> +-0.011064,-0.008217,-0.007698,-0.007382,-0.007118,-0.006982,-0.006508,-0.005957,-0.005545,-0.005212,-0.00494,-0.004718,-0.004163,-0.003863,-0.003636,-0.003108,-0.002726,-0.002396,-0.002035,-0.00169,-
Looks good

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00151__20210804__CC_tcarray.ext
> +-0.010408,-0.005205,-0.004321,-0.003693,-0.002975,-0.002736,-0.002462,-0.002382,-0.002283,-0.002183,-0.001928,-0.001907,-0.001781,-0.001776,-0.001436,-0.001356,-0.001153,-0.001109,-0.000898,-0.000759
Looks good

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00256__20210811.csv
> +ACS-256,CC_tcarray,SheetRef:CC_tcarray,
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00256__20210811__CC_taarray.ext
> +-0.013294,-0.008875,-0.006278,-0.005785,-0.005166,-0.004557,-0.003943,-0.003326,-0.002763,-0.002189,-0.001694,-0.001158,-0.000744,-0.000578,-0.000209,2.3e-05,0.000189,0.000503,0.000635,0.000577,0.000
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/PHSEND/CGINS-PHSEND-P0155__20210716.csv
> +P0155,CC_psal,35,Constant
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/OPTAAD/CGINS-OPTAAD-00256__20210811__CC_tcarray.ext
> +-0.012576,-0.010497,-0.009432,-0.009013,-0.008594,-0.008414,-0.008126,-0.007785,-0.007406,-0.007066,-0.006546,-0.006022,-0.005546,-0.005075,-0.004607,-0.004224,-0.003753,-0.002978,-0.002505,-0.001979
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/ADCPAM/CGINS-ADCPAM-44067__20150110.csv
> +644067,CC_scale_factor4,0.61,
Looks good.

2021-08-31 22:26 UTC, reedan88 commented on calibration/ADCPAM/CGINS-ADCPAM-49653__20150110.csv
> +649653,CC_scale_factor4,0.61,
Looks good.

2021-08-31 23:21 UTC, rtravis-whoi commented on calibration/PHSEND/CGINS-PHSEND-P0155__20210716.csv
> +P0155,CC_ea434,17372.0, source_file PHSEN-D_SAMI_pH_SN_P0155_Validation_Files_2021-07-16.zip > Val_Certificate_P0155.pdf
All set!

2021-09-01 14:55 UTC, reedan88 approved these changes
Edit to PHSEN source file name looks good.

2021-09-01 14:55 UTC, reedan88 commented on calibration/PHSEND/CGINS-PHSEND-P0155__20210716.csv
> +P0155,CC_psal,35,Constant
New source file name looks good!

2021-09-01 16:12 UTC, asmith-whoi approved these changes
Correction noted and approved

2021-09-01 16:12 UTC, asmith-whoi commented on calibration/PHSEND/CGINS-PHSEND-P0155__20210716.csv
> +P0155,CC_psal,35,Constant
Source file name good

2021-09-01 16:55 UTC, merged