Pioneer 18 precruise SM deploy csvs
WHOIGit/ooicgsn-asset-management pull request #855
Opened 2022-04-01 14:26 UTC by rtravis-whoi

2022-04-04 18:26 UTC, rtravis-whoi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pioneer 18 AM Updates [DT-152]](https://trello.com/c/zFi7BfCv/152-pioneer-18-am-updates-dt-152)

2022-04-04 20:47 UTC, reedan88 requested changes
I spotted only one error with a missing deployment depth for OSSM MFN OPTAA

2022-04-04 20:47 UTC, reedan88 commented on deployment/CP01CNSM_Deploy.csv
> +AR66,,,,CP01CNSM-SBD12-08-FDCHPA000,16,1,2022-04-08T12:00:00,,CGMCP-01CNSM-00016,,CGINS-FDCHPB-11802,40.1,-70.7,,-5,132,,,
Looks good.

2022-04-04 20:47 UTC, reedan88 commented on deployment/CP03ISSM_Deploy.csv
> +AR66,,,,CP03ISSM-SBD12-04-PCO2AA000,15,1,2022-04-08T12:00:00,,CGMCP-03ISSM-00015,,CGINS-PCO2AA-35260,40.3,-70.8,,0,93,,,
Looks good!

2022-04-04 20:47 UTC, reedan88 commented on deployment/CP04OSSM_Deploy.csv
> +AR66,,,,CP04OSSM-MFD37-01-OPTAAD000,15,1,2022-04-08T12:00:00,,CGMCP-04OSSM-00015,,CGINS-OPTAAD-00159,39.9,-70.8,,,445,,,
Missing depth

2022-04-04 20:47 UTC, reedan88 commented on deployment/CP04OSSM_Deploy.csv
> +AR66,,,,CP04OSSM-SBD12-04-PCO2AA000,15,1,2022-04-08T12:00:00,,CGMCP-04OSSM-00015,,CGINS-PCO2AA-34233,39.9,-70.8,,0,445,,,
Looks good.

2022-04-05 13:28 UTC, reedan88 approved these changes
Looks good! Thanks for the fix.

2022-04-05 13:39 UTC, cdobs approved these changes
All pre-deployment configs look good

2022-04-05 13:39 UTC, cdobs commented on deployment/CP01CNSM_Deploy.csv
> +AR66,,,,CP01CNSM-SBD12-08-FDCHPA000,16,1,2022-04-08T12:00:00,,CGMCP-01CNSM-00016,,CGINS-FDCHPB-11802,40.1,-70.7,,-5,132,,,
looks good

2022-04-05 13:39 UTC, cdobs commented on deployment/CP03ISSM_Deploy.csv
> +AR66,,,,CP03ISSM-SBD12-04-PCO2AA000,15,1,2022-04-08T12:00:00,,CGMCP-03ISSM-00015,,CGINS-PCO2AA-35260,40.3,-70.8,,0,93,,,
looks good

2022-04-05 13:39 UTC, cdobs commented on deployment/CP04OSSM_Deploy.csv
> +AR66,,,,CP04OSSM-SBD12-04-PCO2AA000,15,1,2022-04-08T12:00:00,,CGMCP-04OSSM-00015,,CGINS-PCO2AA-34233,39.9,-70.8,,0,445,,,
looks good

2022-04-07 14:07 UTC, merged